### ISSUE TITLE
Routes Exception when using PATCH method

### ISSUE THREAD

**Issue by tfredrich** [RestExpress/RestExpress#123]
I set up a route using the HTTP PATCH method, but I am getting an exception:

Exception in thread "main" java.lang.NullPointerException
	at org.restexpress.route.RouteMapping.addRoute(RouteMapping.java:181)
	at org.restexpress.route.RouteDeclaration$1.process(RouteDeclaration.java:93)
	at org.restexpress.route.RouteDeclaration$1.process(RouteDeclaration.java:85)
	at org.restexpress.route.RouteDeclaration.iterateRouteBuilders(RouteDeclaration.java:108)
	at org.restexpress.route.RouteDeclaration.createRouteMapping(RouteDeclaration.java:84)
	at org.restexpress.RestExpress.createRouteResolver(RestExpress.java:719)
	at org.restexpress.RestExpress.buildRequestHandler(RestExpress.java:583)
	at org.restexpress.RestExpress.bind(RestExpress.java:612)
	at com.myapp.MyApp.initializeServer(MyApp.java:93)
	at com.myapp.MyApp.main(MyApp.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

The route:

server.uri("/users", config.getUsersController())
        .action("updateMore", HttpMethod.PATCH)
        .name(Constants.Routes.USER_COLLECTION);

This doesn't happen with: POST, PUT, DELETE, GET.

**Comment by tfredrich** [comment]
Fix now available on 0.11.3-SNAPSHOT
